// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBJTXNJAM_BC0V7uZhOFco-s8YLcv_poIU',
    appId: '1:165205520567:web:c21321eebb3a91649fdd32',
    messagingSenderId: '165205520567',
    projectId: 'flashchat-96fa6',
    authDomain: 'flashchat-96fa6.firebaseapp.com',
    storageBucket: 'flashchat-96fa6.appspot.com',
    measurementId: 'G-VMN6YG35HN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC5ujkva8NwQr3MLTS1vNU14cnkVvN5luY',
    appId: '1:165205520567:android:04afb4e11aa2b01b9fdd32',
    messagingSenderId: '165205520567',
    projectId: 'flashchat-96fa6',
    storageBucket: 'flashchat-96fa6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBJnI1V5VL4rVZ6pkURfv5rhPQTEdrH43c',
    appId: '1:165205520567:ios:b900e246ecf0cf9c9fdd32',
    messagingSenderId: '165205520567',
    projectId: 'flashchat-96fa6',
    storageBucket: 'flashchat-96fa6.appspot.com',
    iosBundleId: 'com.example.flashChat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBJnI1V5VL4rVZ6pkURfv5rhPQTEdrH43c',
    appId: '1:165205520567:ios:9155f3606ce59b029fdd32',
    messagingSenderId: '165205520567',
    projectId: 'flashchat-96fa6',
    storageBucket: 'flashchat-96fa6.appspot.com',
    iosBundleId: 'com.example.flashChat.RunnerTests',
  );
}
